/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.userInterface.dialogs;

import java.awt.*;

/**
 *
 * @author enrico
 */
public class DescriptionDialog extends javax.swing.JDialog {

    /**
     * Creates new form DescriptionDialog
     */
    public DescriptionDialog(java.awt.Frame parent, boolean modal, String description) {
        super(parent, modal);
        initComponents();
        jTextArea1.setText(description);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Descrizione");
        setMinimumSize(new Dimension(700,300));
        setPreferredSize(new Dimension(750,300));


        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFont(jTextArea1.getFont().deriveFont((float) 18).deriveFont(Font.PLAIN));
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        setLocationRelativeTo(null);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
