/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.userInterface.dialogs;

import entities.Score;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author enrico
 */
public class RankingDialog extends javax.swing.JDialog {

    /**
     * Creates new form RankingDialog
     */
    
    List<Score> scores;
    
    String gameName;
    
    public RankingDialog(java.awt.Frame parent, boolean modal, List<Score> scores, String gameName) {
        super(parent, modal);
        this.scores = scores;
        this.gameName = gameName;
        initComponents();
        init();
    }

    private void init(){
        DefaultTableModel model = (DefaultTableModel) jTableRanking.getModel();

        for(Score score : scores){
            if(score.getGameName().equals(gameName)){
                model.addRow(new Object[]{score.getName(), score.getPoints() + "/" + score.getTotalPoints(), score.getFinalTime().toString()});
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRanking = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RANKING");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTableRanking.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Points", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRanking);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRanking;
    // End of variables declaration//GEN-END:variables
}
